name: Code CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20.5'
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Link build
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test
